// Mocks generated by Mockito 5.4.4 from annotations
// in nasa_pictures/test/presentation/nasa_pictures_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nasa_pictures/usecase/filtering/get_pictures_filtering.dart'
    as _i3;
import 'package:nasa_pictures/usecase/filtering/get_pictures_filtering_in.dart'
    as _i7;
import 'package:nasa_pictures/usecase/filtering/get_pictures_filtering_use_case.dart'
    as _i6;
import 'package:nasa_pictures/usecase/pictures/get_pictures.dart' as _i2;
import 'package:nasa_pictures/usecase/pictures/get_pictures_use_case.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetPictures_0 extends _i1.SmartFake implements _i2.GetPictures {
  _FakeGetPictures_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetPicturesFiltering_1 extends _i1.SmartFake
    implements _i3.GetPicturesFiltering {
  _FakeGetPicturesFiltering_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetPicturesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPicturesUseCase extends _i1.Mock
    implements _i4.GetPicturesUseCase {
  MockGetPicturesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.GetPictures> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<_i2.GetPictures>.value(_FakeGetPictures_0(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i2.GetPictures>);
}

/// A class which mocks [GetPicturesFilteringUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPicturesFilteringUseCase extends _i1.Mock
    implements _i6.GetPicturesFilteringUseCase {
  MockGetPicturesFilteringUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.GetPicturesFiltering> call(_i7.GetPicturesFilteringIn? init) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [init],
        ),
        returnValue: _i5.Future<_i3.GetPicturesFiltering>.value(
            _FakeGetPicturesFiltering_1(
          this,
          Invocation.method(
            #call,
            [init],
          ),
        )),
      ) as _i5.Future<_i3.GetPicturesFiltering>);
}

/// A class which mocks [GetPicturesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPicturesUseCaseRelaxed extends _i1.Mock
    implements _i4.GetPicturesUseCase {
  @override
  _i5.Future<_i2.GetPictures> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<_i2.GetPictures>.value(_FakeGetPictures_0(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.GetPictures>.value(_FakeGetPictures_0(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i2.GetPictures>);
}

/// A class which mocks [GetPicturesFilteringUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPicturesFilteringUseCaseRelaxed extends _i1.Mock
    implements _i6.GetPicturesFilteringUseCase {
  @override
  _i5.Future<_i3.GetPicturesFiltering> call(_i7.GetPicturesFilteringIn? init) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [init],
        ),
        returnValue: _i5.Future<_i3.GetPicturesFiltering>.value(
            _FakeGetPicturesFiltering_1(
          this,
          Invocation.method(
            #call,
            [init],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.GetPicturesFiltering>.value(
            _FakeGetPicturesFiltering_1(
          this,
          Invocation.method(
            #call,
            [init],
          ),
        )),
      ) as _i5.Future<_i3.GetPicturesFiltering>);
}
